version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: emailservice-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emailservice
    ports:
      - "5433:5432"
    volumes:
      - emailservice-postgres-data:/var/lib/postgresql/data
      - ../Migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - emailservice-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  emailservice:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: emailservice
    ports:
      - "5102:5189"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AWS_ACCESS_KEY_ID=AKIA46ALPORVS4J45A54
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=me-central-1
      - ApiSettings__ApiKey=dev-email-service-key-2024
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=emailservice;Username=postgres;Password=postgres
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - emailservice-network

volumes:
  emailservice-postgres-data:

networks:
  emailservice-network:
    driver: bridge
